import { Creator } from "@/components/cards/creator-card"

export const featuredCreators: Creator[] = [
    {
        id: "luna-pixel",
        name: "Luna Pixel",
        handle: "lunapixel",
        avatar: "/avatars/luna-avatar.jpg",
        coverImage: "/portfolio/luna-cover.jpg",
        rating: 4.9,
        reviewCount: 127,
        startingPrice: 35,
        responseTime: "< 2 hrs",
        isVerified: true,
        isAvailable: true,
        specialties: ["Character Cards", "Personas", "Fantasy"],
        completedOrders: 342,
    },
    {
        id: "nova-scribe",
        name: "Nova Scribe",
        handle: "novascribe",
        avatar: "/avatars/marcus-avatar.jpg",
        coverImage: "/portfolio/marcus-cover.jpg",
        rating: 4.8,
        reviewCount: 89,
        startingPrice: 45,
        responseTime: "< 4 hrs",
        isVerified: true,
        isAvailable: true,
        specialties: ["Lorebooks", "Worldbuilding", "Sci-Fi"],
        completedOrders: 215,
    },
    {
        id: "echo-art",
        name: "Echo Art",
        handle: "echoart",
        avatar: "/avatars/aria-avatar.jpg",
        coverImage: "/portfolio/aria-cover.jpg",
        rating: 5.0,
        reviewCount: 64,
        startingPrice: 55,
        responseTime: "< 1 hr",
        isVerified: true,
        isAvailable: false,
        specialties: ["Avatars", "Backgrounds", "Anime"],
        completedOrders: 178,
    },
    {
        id: "myth-weaver",
        name: "Myth Weaver",
        handle: "mythweaver",
        avatar: "/avatars/zephyr-avatar.jpg",
        coverImage: "/portfolio/zephyr-cover.jpg",
        rating: 4.7,
        reviewCount: 156,
        startingPrice: 40,
        responseTime: "< 6 hrs",
        isVerified: true,
        isAvailable: true,
        specialties: ["Prompt Packs", "Character Cards", "Dark Fantasy"],
        completedOrders: 421,
    },
]

export const allCreators: Creator[] = [
    ...featuredCreators,
    {
        id: "pixel-dreams",
        name: "Pixel Dreams",
        handle: "pixeldreams",
        avatar: "/avatars/pixel-dreams-avatar.jpg",
        coverImage: "/portfolio/pixel-dreams-cover.jpg",
        rating: 4.6,
        reviewCount: 42,
        startingPrice: 30,
        responseTime: "< 8 hrs",
        isVerified: true,
        isAvailable: true,
        specialties: ["Avatars", "Character Cards", "Cyberpunk"],
        completedOrders: 98,
    },
    {
        id: "story-sage",
        name: "Story Sage",
        handle: "storysage",
        avatar: "/avatars/story-sage-avatar.jpg",
        coverImage: "/portfolio/story-sage-cover.jpg",
        rating: 4.9,
        reviewCount: 203,
        startingPrice: 60,
        responseTime: "< 3 hrs",
        isVerified: true,
        isAvailable: true,
        specialties: ["Lorebooks", "Personas", "Historical"],
        completedOrders: 567,
    },
    {
        id: "dream-weave",
        name: "Dream Weave",
        handle: "dreamweave",
        avatar: "/avatars/dream-weave-avatar.jpg",
        coverImage: "/portfolio/dream-weave-cover.jpg",
        rating: 4.5,
        reviewCount: 31,
        startingPrice: 25,
        responseTime: "< 12 hrs",
        isVerified: false,
        isAvailable: true,
        specialties: ["Character Cards", "Romance", "Slice of Life"],
        completedOrders: 45,
    },
    {
        id: "cosmic-ink",
        name: "Cosmic Ink",
        handle: "cosmicink",
        avatar: "/avatars/cosmic-ink-avatar.jpg",
        coverImage: "/portfolio/cosmic-ink-cover.jpg",
        rating: 4.8,
        reviewCount: 78,
        startingPrice: 50,
        responseTime: "< 4 hrs",
        isVerified: true,
        isAvailable: false,
        specialties: ["Worldbuilding", "Sci-Fi", "Prompt Packs"],
        completedOrders: 189,
    },
    {
        id: "shadow-craft",
        name: "Shadow Craft",
        handle: "shadowcraft",
        avatar: "/avatars/shadow-craft-avatar.jpg",
        coverImage: "/portfolio/shadow-craft-cover.jpg",
        rating: 4.7,
        reviewCount: 112,
        startingPrice: 45,
        responseTime: "< 5 hrs",
        isVerified: true,
        isAvailable: true,
        specialties: ["Backgrounds", "Horror", "Dark Fantasy"],
        completedOrders: 278,
    },
    {
        id: "aria-writes",
        name: "Aria Writes",
        handle: "ariawrites",
        avatar: "/avatars/aria-writes-avatar.jpg",
        coverImage: "/portfolio/aria-writes-cover.jpg",
        rating: 4.9,
        reviewCount: 95,
        startingPrice: 55,
        responseTime: "< 2 hrs",
        isVerified: true,
        isAvailable: true,
        specialties: ["Personas", "Lorebooks", "Fantasy"],
        completedOrders: 234,
    },
    {
        id: "neon-pulse",
        name: "Neon Pulse",
        handle: "neonpulse",
        avatar: "/avatars/neon-pulse-avatar.jpg",
        coverImage: "/portfolio/neon-pulse-cover.jpg",
        rating: 4.6,
        reviewCount: 67,
        startingPrice: 40,
        responseTime: "< 6 hrs",
        isVerified: true,
        isAvailable: true,
        specialties: ["Character Cards", "Cyberpunk", "Avatars"],
        completedOrders: 156,
    },
    {
        id: "mystic-quill",
        name: "Mystic Quill",
        handle: "mysticquill",
        avatar: "/avatars/mystic-quill-avatar.jpg",
        coverImage: "/portfolio/mystic-quill-cover.jpg",
        rating: 4.8,
        reviewCount: 143,
        startingPrice: 65,
        responseTime: "< 3 hrs",
        isVerified: true,
        isAvailable: false,
        specialties: ["Worldbuilding", "Lorebooks", "High Fantasy"],
        completedOrders: 389,
    },
]

export const categories = [
    {
        id: "character-cards",
        name: "Character Cards",
        description: "Complete AI character definitions with personality, backstory, and dialogue samples",
        count: 234,
        icon: "Users",
    },
    {
        id: "personas",
        name: "Personas",
        description: "Detailed personality profiles optimized for roleplay interactions",
        count: 189,
        icon: "UserCircle",
    },
    {
        id: "lorebooks",
        name: "Lorebooks",
        description: "Rich world lore and context libraries for immersive storytelling",
        count: 145,
        icon: "BookOpen",
    },
    {
        id: "avatars",
        name: "Avatars",
        description: "Custom character portraits and visual representations",
        count: 312,
        icon: "Image",
    },
    {
        id: "backgrounds",
        name: "Backgrounds",
        description: "Scene and environment artwork for visual storytelling",
        count: 178,
        icon: "Palette",
    },
    {
        id: "prompt-packs",
        name: "Prompt Packs",
        description: "Curated prompt collections for specific scenarios and genres",
        count: 98,
        icon: "MessageSquare",
    },
    {
        id: "worldbuilding",
        name: "Worldbuilding Bundles",
        description: "Complete world packages with lore, characters, and settings",
        count: 67,
        icon: "Globe",
    },
]

export const testimonials = [
    {
        id: 1,
        content: "Finally found creators who actually understand what I need. No more explaining what a lorebook is!",
        author: "Alex M.",
        role: "Power User",
        avatar: "/avatars/alex-testimonial.jpg",
    },
    {
        id: 2,
        content: "I doubled my commission income within the first month. The customers here truly value quality work.",
        author: "Sarah K.",
        role: "Verified Creator",
        avatar: "/avatars/sarah-testimonial.jpg",
    },
    {
        id: 3,
        content: "The protected payments and revision system gave me confidence to place my first order. Exceeded expectations!",
        author: "Jordan T.",
        role: "First-time Buyer",
        avatar: "/avatars/jordan-testimonial.jpg",
    },
]

export const stats = {
    ordersCompleted: "12,400+",
    verifiedCreators: "850+",
    averageRating: "4.8",
    avgResponseTime: "< 4 hrs",
}

export const priceRanges = [
    { id: "under-25", label: "Under $25", min: 0, max: 25 },
    { id: "25-50", label: "$25 - $50", min: 25, max: 50 },
    { id: "50-100", label: "$50 - $100", min: 50, max: 100 },
    { id: "over-100", label: "$100+", min: 100, max: Infinity },
]

export const deliveryTimes = [
    { id: "24h", label: "Within 24 hours" },
    { id: "3d", label: "Within 3 days" },
    { id: "7d", label: "Within 7 days" },
    { id: "any", label: "Any time" },
]

export const sortOptions = [
    { id: "relevance", label: "Relevance" },
    { id: "rating", label: "Highest Rated" },
    { id: "price-low", label: "Price: Low to High" },
    { id: "price-high", label: "Price: High to Low" },
    { id: "newest", label: "Newest" },
    { id: "fastest", label: "Fastest Delivery" },
]
